name: CI Pipeline

on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Укажите нужную версию JDK
          distribution: 'adopt'  # Укажите дистрибутив JDK (например, 'adopt', 'zulu', 'temurin')

      - name: Install Maven
        run: |
          sudo apt-get install maven

      - name: Run tests
        run: |
          mvn clean test -Dbrowser=chrome

      - name: Install Allure
        run: |
          sudo apt-get install allure

      - name: Generate Allure report
        run: |
          mvn allure:report

      - name: Publish Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report  # Имя артефакта
          path: target/site/allure-maven-plugin  # Путь к артефакту для загрузки

  download:
    runs-on: ubuntu-latest
    needs: test  # Зависимость от job test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Allure report
        uses: actions/download-artifact@v2
        with:
          name: allure-report  # Имя артефакта, который вы хотите скачать
          path: ./allure-reports  # Путь, куда будет загружен артефакт